import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../constants/constants";

export const buyCryptoStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    padding: 24,
  },
  sectionLabel: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontFamily: FONTS.medium,
    marginBottom: 8,
    marginTop: 8,
  },
  selectorCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.cardBg,
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  assetRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  assetName: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontFamily: FONTS.medium,
  },
  dropdownBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  assetSymbol: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: FONTS.bold,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 64,
    borderWidth: 1,
    borderColor: COLORS.primary,
    marginBottom: 12,
  },
  currencyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingRight: 12,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.1)",
  },
  currencyText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontFamily: FONTS.bold,
  },
  input: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: 24,
    fontFamily: FONTS.bold,
    textAlign: "right",
    marginLeft: 12,
  },
  presetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  presetChip: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 8,
    marginHorizontal: 4,
  },
  presetChipActive: {
    backgroundColor: COLORS.primary,
  },
  presetText: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontFamily: FONTS.medium,
  },
  presetTextActive: {
    color: "white",
    fontWeight: "bold",
  },
  estimateContainer: {
    alignItems: "center",
    marginBottom: 32,
  },
  estimateLabel: {
    color: COLORS.textSecondary,
    fontSize: 12,
    marginBottom: 4,
  },
  estimateValue: {
    color: COLORS.textPrimary,
    fontSize: 20,
    fontFamily: FONTS.bold,
  },
  paymentCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.cardBg,
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
  },
  paymentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cardIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentTitle: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontFamily: FONTS.medium,
  },
  paymentSubtitle: {
    color: COLORS.textSecondary,
    fontSize: 12,
  },
  feeContainer: {
    backgroundColor: "rgba(255,255,255,0.02)",
    padding: 16,
    borderRadius: 12,
    gap: 8,
  },
  feeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  feeLabel: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
  feeValue: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontFamily: FONTS.regular || "System",
  },
  footer: {
    padding: 24,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
    backgroundColor: COLORS.background,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    paddingVertical: 16,
    gap: 8,
    marginBottom: 12,
  },
  actionText: {
    color: "white",
    fontSize: 16,
    fontFamily: FONTS.bold,
  },
  disclaimer: {
    color: COLORS.textSecondary,
    fontSize: 11,
    textAlign: "center",
    lineHeight: 16,
  },
});
