import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../constants/constants";

export const receiveStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.background,
    zIndex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.cardBg,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
  },
  label: {
    color: COLORS.textSecondary,
    fontSize: 13,
    marginBottom: 8,
    fontFamily: FONTS.regular,
  },
  assetSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.cardBg,
    padding: 16,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  assetInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  coinIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  assetName: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontFamily: FONTS.medium,
  },
  networkContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.cardBg,
    padding: 4,
    borderRadius: 12,
    marginBottom: 32,
  },
  networkTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  networkTabActive: {
    backgroundColor: "#3A3A45",
  },
  networkText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: FONTS.medium,
  },
  networkTextActive: {
    color: COLORS.textPrimary,
    fontWeight: "600",
  },
  qrContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  qrPlaceholder: {
    width: 220,
    height: 220,
    backgroundColor: "white",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 8,
    borderColor: "white",
  },
  addressTitle: {
    textAlign: "center",
    color: COLORS.textSecondary,
    fontSize: 12,
    marginBottom: 8,
  },
  addressBox: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    borderStyle: "dashed",
  },
  addressText: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: 14,
    fontFamily: FONTS.regular || "System",
    marginRight: 12,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginBottom: 32,
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 4,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 24,
    gap: 8,
  },
  actionText: {
    color: COLORS.primary,
    fontSize: 15,
    fontFamily: FONTS.medium,
  },
  dividerVertical: {
    width: 1,
    height: 24,
    backgroundColor: COLORS.border,
  },
  warningContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(247, 147, 26, 0.1)",
    padding: 16,
    borderRadius: 12,
    gap: 12,
  },
  warningText: {
    flex: 1,
    color: "#F7931A",
    fontSize: 12,
    lineHeight: 18,
  },
});
